name: Generate Podcast Feeds
on: [push]
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkcout Repo
        uses: actions/checkout@v3
      - name: Run Feed Generator
        uses: bizbunny/podcast-generator@main
